# yaml-language-server: $schema=../../../llmutils-dev/schema/rmplan-config-schema.json

paths:
  tasks: tasks
models:
  stepGeneration: google/gemini-2.5-flash-preview-05-20
defaultExecutor: claude-code
postApplyCommands:
  # - title: Cleanup Extranous Comments
  #   command: rmplan cleanup
  - title: Format
    command: bun run format
    allowFailure: true
    hideOutputOnSuccess: true
